group 'com.kuku.channel_talk_flutter'
version '1.0'

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.1'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://maven.channel.io/maven2'
            content {
                includeGroup 'io.channel'
            }
        }
    }
}

apply plugin: 'com.android.library'

android {
    namespace "com.kuku.channel_talk_flutter"

    compileSdkVersion 35

    defaultConfig {
        minSdkVersion 21

    }
    lintOptions {
        disable 'InvalidPackage'
    }

    dependencies {
        implementation 'io.channel:plugin-android:13.5.0'
        implementation "com.google.firebase:firebase-messaging:20.1.0"
        testImplementation 'junit:junit:4.13.2'
        testImplementation 'org.mockito:mockito-core:5.14.2'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
